### ISSUE TITLE
Add popular tags, searches and featured states functionality

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/Classified-ads-48#21]
Classified ads are easy to classify as users already went through tagging each listing and also specified it's state. 

- It is easy to run a Mongo query to find out most popular tags and featured states (states with more listings).
- Searches are not cached in MongoDB, so caching is necessary to be able to find popular searches. 

Technically, back-end queries are to be implemented as a CRON job; Front end should be easy to wire either in one page or in three pages.

It is OK to keep cache in-process or if it seems blowing memory or performance, it is fine to add Redis database to the stack !

**Comment by bacloud14** [comment]
Check [indeed](https://www.indeed.com/) under "_What's trending on Indeed"_

**Comment by PranjalAgni** [comment]
Interested to work on this, have some questions:

How are you planning to find the popular searches, maybe if we can introduce text similarity among search terms that will help us to know what is being searched?

Also, I think Redis is the way to go, as that will help to scale even better

**Comment by bacloud14** [comment]
Hello @PranjalAgni 
I'm glad you are contributing to this 😃 

I didn't thought about text similarity, but I think it would be very useful indeed ! As people search very differently for similar things.

Also I agree on Redis, at some point a, in-memory DB would end up in the stack so why not now indeed. 

Thanks again !

**Comment by bacloud14** [comment]
If you do, I have one thing to add for Redis. 
On app start, I check if environment is fine as form of safety. You could add something similar for Redis.

Check: 
https://github.com/bacloud14/Classified-ads-48/blob/f8faf34c9f33752c583f957a625a7fe2e2687162/bootstrap.js#L253

**Comment by PranjalAgni** [comment]
Hi @bacloud14, I have done all the setup but need some help with Google Cloud Storage access keys. I don't have a credit card that is required in my country to enable Google Cloud payment.

Let me know, I can reach out to you on some other platform.

**Comment by bacloud14** [comment]
Hi @PranjalAgni Thank you for the follow up.
For the application to bootstrap (at least), you don't need a key. It is when a user posts a listing (upload a file) then it is needed.

Try adding `/creds/dz-listings-219ed1313c57.json` empty file.

I have only a physical access to one key that I cannot access physically these days. If necessary, I send you that next Thursday or Friday.

**Comment by bacloud14** [comment]
With 
```
GCLOUD_STORAGE_BUCKET=dz-listings-donations
CREDS_PATH=./creds/dz-listings-219ed1313c57.json
```

**Comment by PranjalAgni** [comment]
Hi @bacloud14 Can you please push the .prettierrc for the project, it's currently using my system's global prettier settings and always formatting in a different manner.

**Comment by PranjalAgni** [comment]
Also, I am currently planning to introduce some text similarity algorithms these are the few I have used in the past [Levenshtein Distance](https://en.wikipedia.org/wiki/Levenshtein_distance), [Jaro Winkler Distance](https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance). We can also research for others and can go with the best suited for our use case.

One thing I would like to call out is these algorithms are based on text similarity and do not understand natural language semantics as the ML model does. So `javascript` and `java` would be similar according to any string metric algorithm

**Comment by bacloud14** [comment]
hello @PranjalAgni ,
Thank you for the follow up, it seems going well I'm happy you are going through this.

**prettier** at least in this laptop that I don't use generally for programming, is not configured and probably working with default values (if there are any ?).  But such file `.prettierc` isn't in `.gitignore` so probably is just lacking also in my project; I really didn't pay attention, I can only check next Thrisday or Friday.

**Comment by bacloud14** [comment]
About string similarity, we are heading to a new functionality and this is already exciting. Setting the patterns and minimal required for this to work is great already.
I know a bit about NLP and ML and so, I got your idea. So yes, no problems, let it be simple algorithmic similarity for now 💯

**Comment by bacloud14** [comment]
I sent you a mail./

**Comment by bacloud14** [comment]
Hello @PranjalAgni 
Any follow up for this issue?
Good luck 🍀

**Comment by bacloud14** [comment]
So cool, take your time !

**Comment by PranjalAgni** [comment]
For top search, we can use this route `listings/autocomplete/:search` which will increment the `timeSearched` for the current search term, now we can create a new route `trending/searches` which will return us the top search terms from MongoDB.

What we can do instead of using CRON is, we can set the results in redis which will automatically get expire in x minutes that will make sure that queries to MongoDB are only fired when the cache is evicted.

**Comment by PranjalAgni** [comment]
With the same flow we can go for popular tags and featured states

**Comment by bacloud14** [comment]
I suggest the other "regular" search endpoint

https://github.com/bacloud14/Classified-ads-48/blob/7e4fb8fc12c7179eaf31cab6c1f6a25cbae6b00a/lib/routes/listings.js#L98

 and not `listings/autocomplete/:search`. Just because the autocomplete functionality has already a very limited data-sets of pre-calculated keywords fired at startup (although to be revised for regular updates)

https://github.com/bacloud14/Classified-ads-48/blob/7e4fb8fc12c7179eaf31cab6c1f6a25cbae6b00a/bootstrap.js#L329

**Comment by bacloud14** [comment]
Search section [here](https://dzlistings.herokuapp.com/listings/donations) or [here](https://dzlistings.herokuapp.com/listings)

**Comment by PranjalAgni** [comment]
Sorry, got a lot involved with work this week was not able to invest time in it. Planning for next week will let you know.

**Comment by bacloud14** [comment]
Sure @PranjalAgni just wanted to know. Take your time! 
Thank you

**Comment by bacloud14** [comment]
Hello @PranjalAgni 
Please check
https://github.com/bacloud14/Classified-ads-48/discussions/50
Trying to fix bugs quickly
Thanks

**Comment by PranjalAgni** [comment]
Hi @bacloud14, sorry was not able to focus a lot on it due to work, I will be on vacation next week will try to work on this.

**Comment by PranjalAgni** [comment]
> Hello @PranjalAgni Please check #50 Trying to fix bugs quickly Thanks

This looks good to me, auth0 is good

**Comment by bacloud14** [comment]
Cool. Thank you @PranjalAgni

**Comment by bacloud14** [comment]
Hello @PranjalAgni ,
Your idea of string similarity is great, 
Still willing to work on this ? if not motivated or busy, I can work on this. 
You are always welcome to collab 💯
