### ISSUE TITLE
From JavaScript to typescript

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/Classified-ads-48#54]
https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html

**Comment by jimmywarting** [comment]
why? you can have as good type safety with plain js and without wastful compilation 

beside, typescript + esm is so bad right now...

**Comment by bacloud14** [comment]
I'm really a caveman when it comes to modern JavaScript and already went through a lot of progress in terms of modularity and clean code.

I thought it is an added value but I agree that safety could be achieved anyway so yes, probably not going through this especially if it adds dependencies and constraints.

Thanks Jimmy.

**Comment by bacloud14** [comment]
Otherwise, I'm trying to make a cleaner code for follow contributors. So much going on also for safety, 
Check these:
https://github.com/bacloud14/Classified-ads-48/issues/59
https://github.com/bacloud14/Classified-ads-48/issues/49

I'm pointing some obvious starting tasks as `TODO`s.


Thanks @jimmywarting
